Lua/APR 0.6-2 release and rockspec
Graham Wakefield reports that LuaRocks on Mac OS X complains about
the ZIP archive lua-apr-0.6-1.zip with the following output:

  $ luarocks install http://github.com/xolox/lua-apr/raw/master/etc/lua-apr-0.6-1.rockspec
  Archive:  lua-apr-0.6-1.zip
    End-of-central-directory signature not found.  Either this file is
    not a zipfile, or it constitutes one disk of a multi-part archive.
    In the latter case the central directory and zipfile comment will be
    found on the last disk(s) of this archive.
  unzip: cannot find zipfile directory in one of lua-apr-0.6-1.zip or
    lua-apr-0.6-1.zip.zip, and cannot find lua-apr-0.6-1.zip.ZIP, period.

  Error: Directory lua-apr-0.6-1 not found inside archive lua-apr-0.6-1.zip

I created lua-apr-0.6-1.zip using the GNOME archive manager File Roller
but have since switched to creating ZIP archives using the "package"
rule in the UNIX makefile which uses the "zip" command line program.
Here's hoping this solves the problem...